### ISSUE TITLE
Mercedes - Weeks 1 and 2

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/SULI2020#5]
- [x] PNNL training
- [x] Scientific background reading
- [x] Go over expectations, meeting and update schedule
- [x] Create repository ~(or branch?)~ for her work
- [x] Assessment of where she is, R-wise
- [x] BBL and SP to identify initial R skills work
- [x] Download and install [R](https://www.r-project.org/) and [RStudio](https://rstudio.com/products/rstudio/download/)
- [x] After that, go through Ben's [VCU presentation](https://rpubs.com/bpbond/r-data-vcu) and try out the exercises in it
- [x] Install the `cosore` package using the command `devtools::install_github('/bpbond/cosore')`

**Comment by bpbond** [comment]
Suggested reading list for first three weeks; we can plan for example on reading the first two this week and discussing them early next week. These readings build outward in spatial scale, but microbial studies to cross-site syntheses.

## Week 1 (May 26):

Schimel 2005, "Changing microbial substrate use in Arctic tundra soils through a freeze-thaw cycle" https://www.sciencedirect.com/science/article/pii/S0038071705000209

Haei 2011, "Effects of soil frost on growth, composition and respiration of the soil microbial decomposer community" https://www.sciencedirect.com/science/article/pii/S0038071711002343

## Week 2 (June 1):

Aanderud 2013, "Sensitivity of soil respiration and microbial communities to altered snowfall" https://www.sciencedirect.com/science/article/pii/S0038071712002970

Wang 2014, "Non‐growing‐season soil respiration is controlled by freezing and thawing processes in the summer monsoon‐dominated Tibetan alpine grassland" https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2013GB004760

Wang 2013, "Seasonality of soil CO2 efflux in a temperate forest: Biophysical effects of snowpack and spring freeze–thaw cycles" https://www.sciencedirect.com/science/article/pii/S0168192313000853

## Week 3 (June 8)

Matzner 2008, "Do freeze‐thaw events enhance C and N losses from soils of different ecosystems? A review" https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2389.2007.00992.x

Kim 2012, "Effects of soil rewetting and thawing on soil gas fluxes: a review of current literature and suggestions for future research" https://www.biogeosciences.net/9/2459/2012/

**Comment by mlkhorn** [comment]
Sounds like a good plan!

**Comment by bpbond** [comment]
This week: combination of background (Monday discussion), R review and exercises, and introduction to Git and GitHub.

By end of Monday, @bpbond and @stephpenn1 to assign some online reading/exercises in Git.
By Wednesday morning meeting, @mlkhorn to do those, and then we will all walk through repository creation, Rstudio project creation, branching, and creating a PR, and merging.
By Friday, MH to open a PR with solutions to R exercises we'll have for you on Wednesday.
